export type VisualAssetKind = 'character' | 'scene' | 'prop' | 'shot' | 'story';

export interface TemplateArgument {
  key: string;
  label: string;
  type: 'text' | 'select';
  default: string;
  options?: string[];
  assetField?: string;
}

export interface VisualTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  subcategory: string;
  outputType: 'image' | 'video';
  appliesTo: VisualAssetKind[];
  arguments: TemplateArgument[];
  buildPrompt: (args: Record<string, string>) => string;
}

const baseCharacterArgs: TemplateArgument[] = [
  { key: 'name', label: '角色名', type: 'text', default: '', assetField: 'name' },
  { key: 'appearance', label: '外貌描述', type: 'text', default: '', assetField: 'appearance' },
  { key: 'clothing', label: '服装系统', type: 'text', default: '', assetField: 'clothing' },
  { key: 'personality', label: '气质/性格', type: 'text', default: '', assetField: 'personality' },
  { key: 'visualAnchor', label: '视觉锚点', type: 'text', default: '', assetField: 'visualAnchor' },
  { key: 'colorPalette', label: '色彩方案', type: 'text', default: '', assetField: 'colorPalette' },
];

const baseSceneArgs: TemplateArgument[] = [
  { key: 'name', label: '场景名', type: 'text', default: '', assetField: 'name' },
  { key: 'sceneType', label: '空间类型', type: 'text', default: '', assetField: 'sceneType' },
  { key: 'atmosphere', label: '氛围', type: 'text', default: '', assetField: 'atmosphere' },
  { key: 'materials', label: '材质/视觉元素', type: 'text', default: '', assetField: 'materials' },
  { key: 'landmarks', label: '地标/关键物件', type: 'text', default: '', assetField: 'landmarks' },
  { key: 'colorTemperature', label: '色温/主色调', type: 'text', default: '', assetField: 'colorTemperature' },
  { key: 'visualAnchor', label: '视觉锚点', type: 'text', default: '', assetField: 'visualAnchor' },
];

const basePropArgs: TemplateArgument[] = [
  { key: 'name', label: '道具名', type: 'text', default: '', assetField: 'name' },
  { key: 'dramaticFunction', label: '戏剧功能', type: 'text', default: '', assetField: 'dramaticFunction' },
  { key: 'form', label: '形态结构', type: 'text', default: '', assetField: 'form' },
  { key: 'material', label: '材质', type: 'text', default: '', assetField: 'material' },
  { key: 'surfaceState', label: '表面状态', type: 'text', default: '', assetField: 'surfaceState' },
  { key: 'visualAnchor', label: '视觉锚点', type: 'text', default: '', assetField: 'visualAnchor' },
];

const baseShotArgs: TemplateArgument[] = [
  { key: 'shotTitle', label: '镜头标题', type: 'text', default: '', assetField: 'name' },
  { key: 'sceneType', label: '场景类型', type: 'text', default: '', assetField: 'sceneType' },
  { key: 'copyArea', label: '镜头正文/复制区', type: 'text', default: '', assetField: 'copyArea' },
  { key: 'characters', label: '角色', type: 'text', default: '', assetField: 'characters' },
  { key: 'action', label: '主体动作', type: 'text', default: '', assetField: 'action' },
  { key: 'emotion', label: '情绪', type: 'text', default: '', assetField: 'emotion' },
  { key: 'camera', label: '镜头/机位', type: 'text', default: 'medium shot' },
  { key: 'lighting', label: '光照', type: 'text', default: 'cinematic practical lighting' },
];

const storyArgs = (count: number): TemplateArgument[] => [
  { key: 'storyTitle', label: '故事/段落名', type: 'text', default: '' },
  { key: 'style', label: '故事版风格', type: 'select', default: 'clean black-and-white storyboard line art', options: ['clean black-and-white storyboard line art', 'cinematic color concept art', 'anime storyboard', 'rough director storyboard'] },
  ...Array.from({ length: count }, (_, index) => ({
    key: `panel${index + 1}`,
    label: `Panel ${index + 1}`,
    type: 'text' as const,
    default: '',
  })),
];

const panelText = (a: Record<string, string>, count: number) =>
  Array.from({ length: count }, (_, index) => `Panel ${index + 1}: ${a[`panel${index + 1}`] || (index === 0 ? 'opening image' : index === count - 1 ? 'closing image' : 'story beat')}`).join('\n');

const T: VisualTemplate[] = [
  {
    id: 'character_turnaround_3_view',
    title: '角色三视图',
    description: '正面、侧面、背面，同一人物、五官一致、服装一致、干净背景',
    category: '角色设计',
    subcategory: '三视图',
    outputType: 'image',
    appliesTo: ['character'],
    arguments: [...baseCharacterArgs, { key: 'style', label: '画风', type: 'select', default: 'film character design sheet', options: ['film character design sheet', 'anime character design sheet', 'realistic concept art'] }],
    buildPrompt: (a) => [
      `── CHARACTER TURNAROUND SHEET ──`,
      ``,
      `[SUBJECT] ${a.name || 'the character'}`,
      `[LAYOUT] Three full-body views in one image: FRONT (center), 3/4 SIDE (left), BACK (right). All views aligned on the same ground plane, equal scale.`,
      ``,
      `[IDENTITY — do not alter across views]`,
      a.appearance ? `  Face & Features: ${a.appearance}` : '',
      a.clothing ? `  Costume Layers: ${a.clothing}` : '',
      a.visualAnchor ? `  Signature Element: ${a.visualAnchor}` : '',
      a.colorPalette ? `  Color Palette: ${a.colorPalette}` : '',
      a.personality ? `  Posture & Screen Presence: ${a.personality}` : '',
      ``,
      `[COMPOSITION] Clean white or light gray studio background. Even, soft studio lighting with no dramatic shadows. Each view shows the complete silhouette from head to toe.`,
      `[STYLE] ${a.style || 'film character design sheet'}. Production-ready reference quality.`,
      `[CONSISTENCY] Same face, same hairstyle, same body proportion, same costume layers, same accessories across all three views. The character must be immediately recognizable as the same person.`,
      `[RULES] No watermark, no text overlay, no extra characters, no props unless part of the costume.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'character_portrait_costume',
    title: '角色定妆照',
    description: '角色全身定妆照，展示完整造型与气质',
    category: '角色设计',
    subcategory: '定妆照',
    outputType: 'image',
    appliesTo: ['character'],
    arguments: baseCharacterArgs,
    buildPrompt: (a) => [
      `── CHARACTER COSTUME PORTRAIT ──`,
      ``,
      `[SUBJECT] Full-body portrait of ${a.name || 'the character'}, standing in a relaxed but screen-ready pose.`,
      ``,
      `[IDENTITY]`,
      a.appearance ? `  Face & Features: ${a.appearance}` : '',
      a.clothing ? `  Costume: ${a.clothing} — show every layer, texture, and accessory in full detail` : '',
      a.visualAnchor ? `  Signature Element: ${a.visualAnchor} — must be clearly visible` : '',
      a.colorPalette ? `  Palette: ${a.colorPalette}` : '',
      a.personality ? `  Screen Presence: ${a.personality}` : '',
      ``,
      `[COMPOSITION] Full body from head to toe, 3/4 angle, clean neutral background with subtle gradient. Character occupies 70-80% of frame height.`,
      `[LIGHTING] Soft key light from upper-left, gentle fill, subtle rim light separating the character from background. Production still quality.`,
      `[DETAIL] Show fabric weave, stitching, material texture, shoe detail, hair strand definition, skin pore-level realism.`,
      `[RULES] No watermark, no text overlay, no extra characters, no cropping.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'character_expression_sheet_9',
    title: '角色表情九宫格',
    description: '3x3 表情表，保持五官与服装一致',
    category: '角色设计',
    subcategory: '表情表',
    outputType: 'image',
    appliesTo: ['character'],
    arguments: baseCharacterArgs,
    buildPrompt: (a) => [
      `── CHARACTER EXPRESSION SHEET (3×3 Grid) ──`,
      ``,
      `[SUBJECT] ${a.name || 'the character'} — close-up bust shots only, from chest up.`,
      ``,
      `[IDENTITY — LOCKED across all 9 panels]`,
      a.appearance ? `  Face: ${a.appearance}` : '',
      a.clothing ? `  Costume (visible collar/neckline): ${a.clothing}` : '',
      a.visualAnchor ? `  Signature: ${a.visualAnchor}` : '',
      ``,
      `[LAYOUT] 3×3 grid, 9 panels, each showing the SAME character with a DIFFERENT expression:`,
      `  Row 1: Neutral | Gentle Smile | Suspicion`,
      `  Row 2: Cold Anger | Deep Sadness | Shock/Surprise`,
      `  Row 3: Fear | Restrained Tears | Silent Resolve`,
      ``,
      `[CONSISTENCY] Same face shape, same hairstyle, same skin tone, same lighting setup across ALL 9 panels. Only the eyebrows, mouth, and eye openness change.`,
      `[STYLE] Clean reference-sheet layout, even spacing, uniform panel size, soft studio lighting.`,
      `[RULES] No watermark, no text labels, no background variation, no costume changes.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'character_action_pose_sheet',
    title: '角色动作姿态表',
    description: '展示角色在剧情中的关键动作姿态',
    category: '角色设计',
    subcategory: '动作姿态',
    outputType: 'image',
    appliesTo: ['character'],
    arguments: [...baseCharacterArgs, { key: 'actionSet', label: '动作组', type: 'text', default: 'standing alert, walking, turning back, reaching out, kneeling, running' }],
    buildPrompt: (a) => [
      `── CHARACTER ACTION POSE SHEET ──`,
      ``,
      `[SUBJECT] ${a.name || 'the character'} — six full-body dynamic poses.`,
      `[IDENTITY] Face: ${a.appearance || 'consistent'}. Costume: ${a.clothing || 'consistent'}. Signature: ${a.visualAnchor || 'consistent'}.`,
      ``,
      `[POSES] ${a.actionSet || 'standing alert, walking, turning back, reaching out, kneeling, running'}`,
      `[LAYOUT] Six poses arranged in two rows of three, clean white background, each pose with clear readable silhouette and weight distribution.`,
      `[CONSISTENCY] Same body proportion, face, hairstyle, costume, and accessories in every pose. Only the body position changes.`,
      `[RULES] No watermark, no text overlay, no extra characters, no background elements.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'character_poster_main_visual',
    title: '角色主视觉海报',
    description: '单角色主视觉，用于项目封面或宣传图',
    category: '角色设计',
    subcategory: '主视觉',
    outputType: 'image',
    appliesTo: ['character'],
    arguments: [...baseCharacterArgs, { key: 'posterMood', label: '海报情绪', type: 'text', default: 'mysterious cinematic tension' }],
    buildPrompt: (a) => [
      `── CINEMATIC CHARACTER KEY VISUAL ──`,
      ``,
      `[SUBJECT] ${a.name || 'the character'} as the sole focus of a cinematic key visual poster.`,
      `[IDENTITY] Face: ${a.appearance || 'as established'}. Costume: ${a.clothing || 'as established'}. Signature: ${a.visualAnchor || 'prominent in composition'}.`,
      `[MOOD] ${a.posterMood || 'mysterious cinematic tension'}`,
      `[PALETTE] ${a.colorPalette || 'restrained cinematic colors with one accent'}`,
      ``,
      `[COMPOSITION] Rule-of-thirds framing, strong silhouette, character occupies 60% of frame. Dramatic depth-of-field with environmental hints in background.`,
      `[LIGHTING] Dramatic three-point lighting: strong key light, deep shadows, rim light for separation. Film-poster quality.`,
      `[RULES] No title text, no watermark, no extra characters, no UI elements.`,
    ].filter(Boolean).join('\n'),
  },

  {
    id: 'scene_concept_wide_shot',
    title: '场景概念广角图',
    description: '场景建立镜头，强调空间、材质、氛围',
    category: '场景设计',
    subcategory: '概念图',
    outputType: 'image',
    appliesTo: ['scene'],
    arguments: baseSceneArgs,
    buildPrompt: (a) => `Wide establishing concept art of ${a.name || 'the scene'}. Space type: ${a.sceneType}. Atmosphere: ${a.atmosphere}. Materials and surfaces: ${a.materials}. Landmarks: ${a.landmarks}. Color temperature: ${a.colorTemperature}. Visual anchor: ${a.visualAnchor}. Cinematic environment design, detailed physical textures, coherent color palette, no characters unless specified, no watermark, no text overlay.`,
  },
  {
    id: 'scene_interior_design',
    title: '场景室内设定图',
    description: '室内空间布局、陈设、材质与光源',
    category: '场景设计',
    subcategory: '室内',
    outputType: 'image',
    appliesTo: ['scene'],
    arguments: baseSceneArgs,
    buildPrompt: (a) => `Interior production design image for ${a.name || 'the interior scene'}. Space type: ${a.sceneType}. Atmosphere: ${a.atmosphere}. Architectural materials: ${a.materials}. Key set dressing and landmarks: ${a.landmarks}. Lighting color temperature: ${a.colorTemperature}. Visual anchor: ${a.visualAnchor}. Wide lens, readable floor plan feeling, cinematic realism, no people, no watermark, no text.`,
  },
  {
    id: 'scene_mood_board',
    title: '场景氛围板',
    description: '多图拼板，展示材质、光影、色彩和气质',
    category: '场景设计',
    subcategory: '氛围板',
    outputType: 'image',
    appliesTo: ['scene'],
    arguments: baseSceneArgs,
    buildPrompt: (a) => `Create a cinematic mood board for ${a.name || 'the scene'} with 6 visual tiles. Include: one wide environment tile, one material close-up tile, one lighting reference tile, one color palette tile, one prop/detail tile, one atmosphere tile. Scene type: ${a.sceneType}. Atmosphere: ${a.atmosphere}. Materials: ${a.materials}. Landmarks: ${a.landmarks}. Color palette: ${a.colorTemperature}. No text labels, no watermark.`,
  },
  {
    id: 'scene_map_top_down',
    title: '场景俯视布局图',
    description: '顶视图展示空间动线和关键区域',
    category: '场景设计',
    subcategory: '俯视图',
    outputType: 'image',
    appliesTo: ['scene'],
    arguments: baseSceneArgs,
    buildPrompt: (a) => `Top-down environment layout map for ${a.name || 'the scene'}. Space type: ${a.sceneType}. Key zones and landmarks: ${a.landmarks}. Materials: ${a.materials}. Atmosphere: ${a.atmosphere}. Create a clean production layout view showing entrances, paths, key props, camera-friendly areas, and spatial hierarchy. Minimal diagram style, no decorative text, no watermark.`,
  },
  {
    id: 'scene_horror_atmosphere',
    title: '恐怖氛围场景图',
    description: '适合中式恐怖、悬疑、民俗类场景',
    category: '场景设计',
    subcategory: '恐怖氛围',
    outputType: 'image',
    appliesTo: ['scene'],
    arguments: baseSceneArgs,
    buildPrompt: (a) => `Cinematic horror atmosphere concept art for ${a.name || 'the scene'}. Scene type: ${a.sceneType}. Atmosphere: ${a.atmosphere || 'quiet dread, restrained folk horror tension'}. Materials: ${a.materials}. Landmarks: ${a.landmarks}. Color temperature: ${a.colorTemperature || 'cold desaturated shadows with controlled warm practical light'}. Visual anchor: ${a.visualAnchor}. Realistic production design, no monsters unless in the source, no text, no watermark.`,
  },

  {
    id: 'prop_design_sheet',
    title: '道具设定图',
    description: '道具正面、侧面、背面、细节特写',
    category: '道具设计',
    subcategory: '设定图',
    outputType: 'image',
    appliesTo: ['prop'],
    arguments: basePropArgs,
    buildPrompt: (a) => `Product-style prop design sheet for ${a.name || 'the prop'}. Dramatic function: ${a.dramaticFunction}. Form: ${a.form}. Material: ${a.material}. Surface state: ${a.surfaceState}. Visual anchor: ${a.visualAnchor}. Show front view, side view, back view, and close-up detail in one clean reference sheet. Neutral background, realistic material texture, no hands, no characters, no watermark, no text overlay.`,
  },
  {
    id: 'prop_material_detail',
    title: '道具材质细节图',
    description: '强调磨损、纹理、工艺和可触摸质感',
    category: '道具设计',
    subcategory: '材质',
    outputType: 'image',
    appliesTo: ['prop'],
    arguments: basePropArgs,
    buildPrompt: (a) => `Extreme close-up material detail study of ${a.name || 'the prop'}. Material: ${a.material}. Surface state: ${a.surfaceState}. Craft and form: ${a.form}. Dramatic function: ${a.dramaticFunction}. Visual anchor: ${a.visualAnchor}. Macro lens, tactile texture, visible scratches, age marks, edges, seams, realistic lighting, no hands, no text, no watermark.`,
  },
  {
    id: 'prop_exploded_view',
    title: '道具爆炸结构图',
    description: '拆解结构、部件层级和内部机制',
    category: '道具设计',
    subcategory: '结构拆解',
    outputType: 'image',
    appliesTo: ['prop'],
    arguments: basePropArgs,
    buildPrompt: (a) => `Exploded view technical illustration of ${a.name || 'the prop'}. Overall form: ${a.form}. Material: ${a.material}. Mechanism or dramatic use: ${a.dramaticFunction}. Surface state: ${a.surfaceState}. Show separated layers and components floating in order, clean studio background, production design clarity, no text labels unless minimal, no hands, no watermark.`,
  },
  {
    id: 'prop_in_hand_usage',
    title: '道具持握使用图',
    description: '展示道具尺寸和使用方式',
    category: '道具设计',
    subcategory: '使用方式',
    outputType: 'image',
    appliesTo: ['prop'],
    arguments: [...basePropArgs, { key: 'usage', label: '使用方式', type: 'text', default: 'held carefully at chest height' }],
    buildPrompt: (a) => `Usage reference image for ${a.name || 'the prop'}. Show the prop being ${a.usage}, with the prop as the main subject. Dramatic function: ${a.dramaticFunction}. Form: ${a.form}. Material: ${a.material}. Surface state: ${a.surfaceState}. Keep hands neutral and secondary, avoid showing a full character face, realistic scale reference, no text, no watermark.`,
  },
  {
    id: 'prop_product_display',
    title: '道具陈列展示图',
    description: '用于资产库展示的单物体陈列图',
    category: '道具设计',
    subcategory: '陈列',
    outputType: 'image',
    appliesTo: ['prop'],
    arguments: basePropArgs,
    buildPrompt: (a) => `Hero product display image of ${a.name || 'the prop'} on a neutral surface. Form: ${a.form}. Material: ${a.material}. Surface state: ${a.surfaceState}. Dramatic function: ${a.dramaticFunction}. Visual anchor: ${a.visualAnchor}. Soft studio lighting, 45-degree view, realistic scale, crisp detail, no text, no watermark, no hands.`,
  },

  {
    id: 'shot_keyframe_image',
    title: '镜头关键帧',
    description: '单个镜头最有代表性的画面',
    category: '分镜图片',
    subcategory: '关键帧',
    outputType: 'image',
    appliesTo: ['shot'],
    arguments: baseShotArgs,
    buildPrompt: (a) => `Cinematic keyframe for ${a.shotTitle || 'this shot'}. Source shot content: ${a.copyArea}. Scene type: ${a.sceneType}. Characters: ${a.characters}. Main action: ${a.action}. Emotion: ${a.emotion}. Camera: ${a.camera}. Lighting: ${a.lighting}. Film still quality, coherent character continuity, no subtitles, no text overlay, no watermark.`,
  },
  {
    id: 'shot_first_frame',
    title: '镜头首帧',
    description: '用于视频生成的第一帧画面',
    category: '分镜图片',
    subcategory: '首帧',
    outputType: 'image',
    appliesTo: ['shot'],
    arguments: baseShotArgs,
    buildPrompt: (a) => `First frame image for a video shot. Shot: ${a.shotTitle}. Source content: ${a.copyArea}. Scene: ${a.sceneType}. Characters: ${a.characters}. Starting action: ${a.action || 'the moment before the main action begins'}. Camera: ${a.camera}. Lighting: ${a.lighting}. Hold a clear starting composition, cinematic realism, no text, no watermark.`,
  },
  {
    id: 'shot_last_frame',
    title: '镜头尾帧',
    description: '用于视频生成的最后一帧画面',
    category: '分镜图片',
    subcategory: '尾帧',
    outputType: 'image',
    appliesTo: ['shot'],
    arguments: baseShotArgs,
    buildPrompt: (a) => `Last frame image for a video shot. Shot: ${a.shotTitle}. Source content: ${a.copyArea}. Scene: ${a.sceneType}. Characters: ${a.characters}. End state: ${a.action || 'the action resolves into a held final moment'}. Emotion: ${a.emotion}. Camera: ${a.camera}. Cinematic still, clear end composition, no text, no watermark.`,
  },
  {
    id: 'shot_before_after_frame',
    title: '首尾对照图',
    description: '同一画面中呈现首帧和尾帧对照',
    category: '分镜图片',
    subcategory: '首尾对照',
    outputType: 'image',
    appliesTo: ['shot'],
    arguments: baseShotArgs,
    buildPrompt: (a) => `Create a two-panel before/after frame reference for ${a.shotTitle || 'this shot'}. Left panel: first frame before the action. Right panel: last frame after the action. Source content: ${a.copyArea}. Scene: ${a.sceneType}. Characters: ${a.characters}. Camera continuity: ${a.camera}. Keep character design, wardrobe, lighting, and environment consistent across both panels. No watermark, no subtitles, minimal panel separation only.`,
  },
  {
    id: 'shot_continuity_frame',
    title: '镜头连续性参考图',
    description: '帮助多个镜头保持人物、空间和光线连续',
    category: '分镜图片',
    subcategory: '连续性',
    outputType: 'image',
    appliesTo: ['shot'],
    arguments: baseShotArgs,
    buildPrompt: (a) => `Continuity reference frame for ${a.shotTitle || 'this shot'}. Source: ${a.copyArea}. Preserve character wardrobe, facial identity, prop placement, environment layout, and lighting direction. Scene: ${a.sceneType}. Characters: ${a.characters}. Camera: ${a.camera}. Use a production continuity still style, realistic, clean, no text, no watermark.`,
  },
  {
    id: 'shot_camera_movement_diagram',
    title: '镜头运动说明图',
    description: '镜头路径、起幅和落幅的可视化示意',
    category: '分镜图片',
    subcategory: '镜头运动',
    outputType: 'image',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'cameraMovement', label: '镜头运动', type: 'text', default: 'slow dolly-in' }],
    buildPrompt: (a) => `Camera movement diagram for ${a.shotTitle || 'this shot'}. Source content: ${a.copyArea}. Movement: ${a.cameraMovement}. Starting composition: ${a.camera}. Scene: ${a.sceneType}. Show camera path, subject position, start frame, end frame, and spatial relation in a clean director storyboard diagram. No watermark, no decorative text.`,
  },

  {
    id: 'storyboard_4_panel',
    title: '故事版四格',
    description: '4 格故事版，适合短段落快速预览',
    category: '故事版',
    subcategory: '四格',
    outputType: 'image',
    appliesTo: ['shot', 'story'],
    arguments: storyArgs(4),
    buildPrompt: (a) => `Create a 4-panel storyboard sheet for "${a.storyTitle || 'the scene'}". Style: ${a.style}.\n${panelText(a, 4)}\nKeep the same protagonist design and environment continuity across all panels. Clear panel grid, no watermark, no extra explanatory text.`,
  },
  {
    id: 'storyboard_6_panel',
    title: '故事版六格',
    description: '6 格故事版，适合一个 scene 的节奏拆解',
    category: '故事版',
    subcategory: '六格',
    outputType: 'image',
    appliesTo: ['shot', 'story'],
    arguments: storyArgs(6),
    buildPrompt: (a) => `Create a 6-panel storyboard sheet for "${a.storyTitle || 'the scene'}". Style: ${a.style}.\n${panelText(a, 6)}\nMaintain character continuity, spatial continuity, lighting continuity, and readable camera progression. No watermark, no subtitles, no extra explanatory text.`,
  },
  {
    id: 'storyboard_9_panel',
    title: '故事版九宫格',
    description: '9 格故事版，适合完整段落或预告片节奏',
    category: '故事版',
    subcategory: '九宫格',
    outputType: 'image',
    appliesTo: ['shot', 'story'],
    arguments: storyArgs(9),
    buildPrompt: (a) => `Create a 9-panel storyboard sheet in a 3x3 grid for "${a.storyTitle || 'the sequence'}". Style: ${a.style}.\n${panelText(a, 9)}\nThe panels must read as one continuous scene, with consistent protagonist, wardrobe, props, location, and lighting. No watermark, no subtitles, no extra explanatory text.`,
  },
  {
    id: 'storyboard_black_white_lineart',
    title: '黑白线稿故事版',
    description: '导演分镜草图风格，适合剪辑规划',
    category: '故事版',
    subcategory: '黑白线稿',
    outputType: 'image',
    appliesTo: ['shot', 'story'],
    arguments: storyArgs(6),
    buildPrompt: (a) => `Create a black-and-white director storyboard sheet for "${a.storyTitle || 'the scene'}". Use rough but readable line art, clear silhouettes, camera arrows only when helpful.\n${panelText(a, 6)}\nNo shading overload, no watermark, no subtitles, no decorative typography.`,
  },
  {
    id: 'storyboard_cinematic_color',
    title: '电影色彩故事版',
    description: '彩色电影感故事版，适合给图像模型直接生成',
    category: '故事版',
    subcategory: '电影彩色',
    outputType: 'image',
    appliesTo: ['shot', 'story'],
    arguments: storyArgs(6),
    buildPrompt: (a) => `Create a cinematic color storyboard sheet for "${a.storyTitle || 'the scene'}". Use consistent film lighting and color palette.\n${panelText(a, 6)}\nKeep the same character design, scene layout, wardrobe, and prop continuity across panels. No watermark, no subtitles, no extra text.`,
  },

  {
    id: 'video_single_shot',
    title: '单镜头视频提示词',
    description: '把一个 shot 转成可复制的视频生成提示词',
    category: '视频提示词',
    subcategory: '单镜头',
    outputType: 'video',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'duration', label: '时长', type: 'select', default: '5 seconds', options: ['3 seconds', '5 seconds', '8 seconds', '10 seconds'] }, { key: 'cameraMovement', label: '镜头运动', type: 'text', default: 'slow controlled camera movement' }],
    buildPrompt: (a) => [
      `── VIDEO PROMPT (${a.duration || '5 seconds'}) ──`,
      ``,
      `[SHOT] ${a.shotTitle || 'this shot'}`,
      `[ACTION] ${a.action || a.copyArea}`,
      a.characters ? `[CHARACTERS] ${a.characters} — maintain the exact appearance, costume, and visual identity from the reference images. If reference images are provided, match them precisely.` : '',
      `[SCENE] ${a.sceneType || 'cinematic environment'}`,
      `[CAMERA] ${a.camera || 'medium shot'}. Movement: ${a.cameraMovement || 'subtle steady movement'}.`,
      `[EMOTION] ${a.emotion || 'neutral tension'}`,
      `[LIGHTING] ${a.lighting || 'cinematic practical lighting'}`,
      ``,
      `[RULES] Natural motion, physically plausible camera, character continuity throughout the clip. No watermark, no subtitles, no text overlay, no extra characters.`,
      a.characters ? `[IDENTITY NOTE] If you have saved reference images for the characters above, upload them alongside this prompt to ensure visual consistency.` : '',
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'video_first_to_last_frame',
    title: '首帧到尾帧视频提示词',
    description: '明确起幅、过程和落幅，适合图生视频',
    category: '视频提示词',
    subcategory: '首尾帧',
    outputType: 'video',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'firstFrame', label: '首帧', type: 'text', default: '' }, { key: 'lastFrame', label: '尾帧', type: 'text', default: '' }, { key: 'duration', label: '时长', type: 'select', default: '5 seconds', options: ['5 seconds', '8 seconds', '10 seconds'] }],
    buildPrompt: (a) => [
      `── IMAGE-TO-VIDEO PROMPT (${a.duration || '5 seconds'}) ──`,
      ``,
      `[FIRST FRAME] ${a.firstFrame || 'Starting composition: ' + a.camera}`,
      `[MOTION] ${a.action || a.copyArea}`,
      `[LAST FRAME] ${a.lastFrame || 'Hold on the resolved end state'}`,
      a.characters ? `[CHARACTERS] ${a.characters} — must maintain identical appearance throughout. Use the saved reference images as the visual anchor.` : '',
      `[SCENE] ${a.sceneType || 'consistent environment'}`,
      `[LIGHTING] ${a.lighting || 'maintain lighting continuity from first to last frame'}`,
      ``,
      `[RULES] Smooth interpolation between frames. Character identity, costume, and props must not drift. No subtitles, no watermark, no text overlay.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'video_camera_movement',
    title: '镜头运动视频提示词',
    description: '强调推拉摇移、运动节奏和空间关系',
    category: '视频提示词',
    subcategory: '镜头运动',
    outputType: 'video',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'cameraMovement', label: '镜头运动', type: 'text', default: 'slow dolly-in with slight handheld tension' }, { key: 'duration', label: '时长', type: 'select', default: '5 seconds', options: ['5 seconds', '8 seconds', '10 seconds'] }],
    buildPrompt: (a) => [
      `── CAMERA MOVEMENT VIDEO (${a.duration || '5 seconds'}) ──`,
      ``,
      `[CAMERA] ${a.cameraMovement || 'slow dolly-in'}. Starting frame: ${a.camera || 'medium shot'}.`,
      `[CONTENT] ${a.action || a.copyArea}`,
      a.characters ? `[CHARACTERS] ${a.characters} — maintain identical visual identity. Attach reference images if available.` : '',
      `[SCENE] ${a.sceneType}. [EMOTION] ${a.emotion || 'neutral'}.`,
      `[RULES] Physically plausible camera path, stable subject continuity, cinematic timing. No watermark, no subtitles, no text overlay.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'video_seedance_style',
    title: 'Seedance 风格视频提示词',
    description: '偏向即梦/Seedance 的自然语言视频提示词',
    category: '视频提示词',
    subcategory: 'Seedance',
    outputType: 'video',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'duration', label: '时长', type: 'select', default: '5 seconds', options: ['5 seconds', '10 seconds', '15 seconds'] }, { key: 'environmentMotion', label: '环境动态', type: 'text', default: 'subtle ambient movement' }],
    buildPrompt: (a) => [
      `── SEEDANCE VIDEO (${a.duration || '5 seconds'}) ──`,
      ``,
      `[SHOT] ${a.copyArea}`,
      `[ACTION] ${a.action || 'as described above'}`,
      a.characters ? `[CHARACTERS] ${a.characters} — strict visual identity consistency. If reference images exist for these characters, attach them to this prompt.` : '',
      `[SCENE] ${a.sceneType}. [CAMERA] ${a.camera}. [LIGHTING] ${a.lighting}.`,
      `[ENVIRONMENT MOTION] ${a.environmentMotion || 'subtle ambient movement'}`,
      `[RULES] Preserve script facts only. Do not add new plot. Natural motion, no subtitles, no text overlay, no watermark.`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'video_jimeng_kling_style',
    title: '即梦/可灵风格视频提示词',
    description: '适合中文网页视频模型复制使用',
    category: '视频提示词',
    subcategory: '即梦/可灵',
    outputType: 'video',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'duration', label: '时长', type: 'select', default: '5秒', options: ['5秒', '8秒', '10秒'] }, { key: 'motionDetail', label: '运动细节', type: 'text', default: '人物动作自然，环境轻微流动，镜头缓慢推进' }],
    buildPrompt: (a) => [
      `── 即梦/可灵 视频提示词 (${a.duration || '5秒'}) ──`,
      ``,
      `镜头内容：${a.copyArea}`,
      `场景类型：${a.sceneType}`,
      a.characters ? `出场角色：${a.characters}。要求人物面容、发型、服装、体型与参考图完全一致。如有已保存的角色参考图，请一并上传。` : '',
      `主体动作：${a.action}`,
      `情绪：${a.emotion}`,
      `镜头：${a.camera}。光线：${a.lighting}`,
      `运动细节：${a.motionDetail || '人物动作自然，环境轻微流动'}`,
      ``,
      `要求：人物身份、服装、空间、道具保持连续。不添加剧本外情节，不要字幕，不要水印，不要文字叠加。`,
    ].filter(Boolean).join('\n'),
  },
  {
    id: 'video_transition',
    title: '镜头转场提示词',
    description: '两个镜头之间的衔接/转场视频描述',
    category: '视频提示词',
    subcategory: '转场',
    outputType: 'video',
    appliesTo: ['shot'],
    arguments: [...baseShotArgs, { key: 'previousState', label: '上一镜尾态', type: 'text', default: '' }, { key: 'nextState', label: '下一镜首态', type: 'text', default: '' }, { key: 'transitionType', label: '转场方式', type: 'text', default: 'match cut through motion continuity' }],
    buildPrompt: (a) => `Video transition prompt. Previous shot end state: ${a.previousState}. Transition type: ${a.transitionType}. Next shot start state: ${a.nextState}. Current source shot context: ${a.copyArea}. Maintain character, prop, location, and lighting continuity. The transition must feel motivated by motion or composition, no text, no subtitles, no watermark.`,
  },
];

export const TEMPLATE_CATEGORIES = [...new Set(T.map((t) => t.category))];

export function getTemplatesByCategory(category: string) {
  return T.filter((t) => t.category === category);
}

export function getTemplateById(id: string) {
  return T.find((t) => t.id === id);
}

export function getAllTemplates() {
  return T;
}

export default T;
